apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: lembas
servers: 1
agents: 1
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
registries:
  create:
    name: k3d-tilt-registry
    host: 0.0.0.0
    hostPort: random
# volumes:
#   - volume: $HOME/lembas_local_storage:/var/lib/rancher/k3s/storage@all
#     nodeFilters:
#       - all

options:
  k3s:
    extraArgs:
      - arg: --kubelet-arg=eviction-hard=imagefs.available<1%,nodefs.available<1%
        nodeFilters:
          - agent:*
      - arg: --kubelet-arg=eviction-minimum-reclaim=imagefs.available=1%,nodefs.available=1%
        nodeFilters:
          - agent:*
