repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: fix-byte-order-marker
  - id: check-case-conflict
  - id: debug-statements
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: trailing-whitespace
- repo: https://github.com/asottile/pyupgrade
  rev: v3.19.1
  hooks:
  - id: pyupgrade
- repo: https://github.com/anaconda/pre-commit-hooks
  rev: v24.5.2
  hooks:
  - id: generate-renovate-annotations
    args:
    - --create-command
    - conda project install --all
    - --environment-selector
    - -p ./envs/dev
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.6
  hooks:
  - id: ruff
    args: [--fix]
  - id: ruff-format
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]
  - id: pretty-format-toml
    args: [--autofix]
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v2.5.1
  hooks:
  - id: prettier
    files: \.(js|css|html|json)$
    exclude: \.min\.js
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.30.0
  hooks:
  - id: check-github-workflows
  - id: check-renovate
- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell
    exclude: \.min\.js
- repo: meta
  hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes
