name: dev
channels:
  - conda-forge
dependencies:
  # renovate: datasource=conda depName=conda-forge/pytest
  - pytest=8.3.4
  # renovate: datasource=conda depName=conda-forge/pre-commit
  - pre-commit=4.0.1
  # renovate: datasource=conda depName=conda-forge/httpx
  - httpx=0.28.0
  # renovate: datasource=conda depName=conda-forge/pytest-asyncio
  - pytest-asyncio=0.24.0
  # renovate: datasource=conda depName=conda-forge/mypy
  - mypy=1.13.0
variables:
prefix:
platforms:
  - osx-arm64
  - linux-64
