app = "lembas"
primary_region = "dfw"

[build]

[deploy]
release_command = "alembic upgrade head"

[env]
CLIENT_ID = "Ov23liZQ3GSRQrONST3V"
DATABASE_URL = "sqlite+aiosqlite:///data/lembas.db"
# CLIENT_SECRET is set as a secret in fly.io
REDIRECT_URL = "https://lembas.matt-kramer.com"

[http_service]
auto_start_machines = true
auto_stop_machines = "stop"
force_https = true
internal_port = 8000
min_machines_running = 0
processes = ["app"]

[mounts]
destination = "/app/data"
source = "lembas_data"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
