ports:
- name: http
  containerPort: 8000
  protocol: TCP

livenessProbe:
  httpGet:
    path: /api/healthz

readinessProbe:
  httpGet:
    path: /api/healthz

autoscaling:
  enabled: false

podDisruptionBudget:
  enabled: false

ingress:
  enabled: true
  hosts:
  - host: lembas.localhost
    paths:
    - path: /
      pathType: Prefix
      servicePortName: http

env:
  REDIRECT_URL: http://lembas.localhost
  TOKEN_URL: https://github.com/login/oauth/access_token
  LOGIN_URL_BASE: https://github.com/login/oauth/authorize

envValueFrom:
  CLIENT_ID:
    secretKeyRef:
      name: secrets
      key: CLIENT_ID
  CLIENT_SECRET:
    secretKeyRef:
      name: secrets
      key: CLIENT_SECRET
