name: Deploy
on:
  push:
    branches:
    - main
  pull_request:
jobs:
  deploy:
    name: Deploy app to fly.io
    runs-on: ubuntu-latest
    concurrency: deploy-group    # ensure only one action runs at a time
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683   # v4.2.2
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - run: make deploy
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
